title: NorppaTurva
description: Proposal for a digital fishing equipment registry and targeted monitoring to protect the endangered Saimaa ringed seal
theme: jekyll-theme-cayman
google_analytics: G-DR9HYMWWXW